# Generated by Django 4.2 on 2025-11-18 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional friendly name for this banner', max_length=100, null=True)),
                ('page_key', models.CharField(blank=True, help_text='Optional key to target a specific page', max_length=50, null=True)),
                ('title_text', models.CharField(blank=True, help_text='Main heading to show on the banner', max_length=200, null=True)),
                ('subtitle_text', models.CharField(blank=True, help_text='Optional subheading', max_length=200, null=True)),
                ('image', models.ImageField(help_text='Image will be automatically resized for the page title area', upload_to='page_banners/')),
                ('display_order', models.IntegerField(default=0, help_text='Order of appearance (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this banner')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for no end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Title Banner',
                'verbose_name_plural': 'Page Title Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
